//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Controlls/MainMenuInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainMenuInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainMenuInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainMenuInputs"",
    ""maps"": [
        {
            ""name"": ""MainMenuKeyboard"",
            ""id"": ""91cc5cae-71ac-4190-8e83-f8bfe3254c83"",
            ""actions"": [
                {
                    ""name"": ""EnemyClick"",
                    ""type"": ""Button"",
                    ""id"": ""e681f291-569f-4fb0-90de-949fdf273a82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""292897e5-e6a3-4fa6-90a4-4a2a71cd1a0d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnemyClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainMenuKeyboard
        m_MainMenuKeyboard = asset.FindActionMap("MainMenuKeyboard", throwIfNotFound: true);
        m_MainMenuKeyboard_EnemyClick = m_MainMenuKeyboard.FindAction("EnemyClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainMenuKeyboard
    private readonly InputActionMap m_MainMenuKeyboard;
    private IMainMenuKeyboardActions m_MainMenuKeyboardActionsCallbackInterface;
    private readonly InputAction m_MainMenuKeyboard_EnemyClick;
    public struct MainMenuKeyboardActions
    {
        private @MainMenuInputs m_Wrapper;
        public MainMenuKeyboardActions(@MainMenuInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @EnemyClick => m_Wrapper.m_MainMenuKeyboard_EnemyClick;
        public InputActionMap Get() { return m_Wrapper.m_MainMenuKeyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuKeyboardActions set) { return set.Get(); }
        public void SetCallbacks(IMainMenuKeyboardActions instance)
        {
            if (m_Wrapper.m_MainMenuKeyboardActionsCallbackInterface != null)
            {
                @EnemyClick.started -= m_Wrapper.m_MainMenuKeyboardActionsCallbackInterface.OnEnemyClick;
                @EnemyClick.performed -= m_Wrapper.m_MainMenuKeyboardActionsCallbackInterface.OnEnemyClick;
                @EnemyClick.canceled -= m_Wrapper.m_MainMenuKeyboardActionsCallbackInterface.OnEnemyClick;
            }
            m_Wrapper.m_MainMenuKeyboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @EnemyClick.started += instance.OnEnemyClick;
                @EnemyClick.performed += instance.OnEnemyClick;
                @EnemyClick.canceled += instance.OnEnemyClick;
            }
        }
    }
    public MainMenuKeyboardActions @MainMenuKeyboard => new MainMenuKeyboardActions(this);
    public interface IMainMenuKeyboardActions
    {
        void OnEnemyClick(InputAction.CallbackContext context);
    }
}
